import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  SafeAreaView,
  TouchableOpacity,
  Linking,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const TermsOfService = ({ navigation }) => {
  const openEmail = () => {
    Linking.openURL('mailto:7milesnkl@gmail.com');
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton}
          onPress={() => navigation.goBack()}
        >
          <Ionicons name="chevron-back" size={24} color="#1F2937" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 40 }} />
      </View>

      {/* Content */}
      <ScrollView 
        style={styles.scrollView}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Welcome Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Welcome to 7Miles</Text>
          <Text style={styles.contentText}>
            This document is an electronic record in terms of the Information Technology Act, 2000, and the rules thereunder, as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </Text>
          <Text style={styles.contentText}>
            Welcome to 7Miles. 7Miles provides the content and services available on this website subject to the following Terms and Conditions, our Privacy Policy, Payment Policy, Shipping and Return Policy, and other applicable policies you may find throughout our website in relation to specific functionalities, features, or promotions (collectively, the "Terms and Conditions"). By accessing or using this website, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. Please read them carefully before continuing to use our website or services.
          </Text>
        </View>

        {/* Privacy Policy */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Privacy Policy</Text>
          <Text style={styles.contentText}>
            Please review our privacy policy to understand how we collect, use, and safeguard your personal information.
          </Text>
        </View>

        {/* Payment Policy */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payment Policy</Text>
          <Text style={styles.contentText}>
            All purchases made on our platform are subject to our payment policy. For international orders, additional duties or taxes as per local regulations may be applicable, and these charges will be borne by the customer.
          </Text>
        </View>

        {/* Products and Services for Personal Use */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Products and Services for Personal Use</Text>
          <Text style={styles.contentText}>
            All products and services offered on the 7Miles website are intended for personal use only. Commercial resale or redistribution is strictly prohibited unless explicitly authorized by us. We reserve the right to limit or cancel quantities purchased per person, household, or order if misuse or violation is suspected.
          </Text>
        </View>

        {/* Accuracy of Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Accuracy of Information</Text>
          <Text style={styles.contentText}>
            We strive to ensure that all product descriptions, pricing, and other content on our website are accurate and up-to-date. However, we do not warrant that all information is complete, error-free, or current at all times.
          </Text>
        </View>

        {/* Intellectual Property */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Intellectual Property</Text>
          <Text style={styles.contentText}>
            All content on this website—including trademarks, logos, service marks, product images, graphics, and software—is the exclusive property of 7Miles or its affiliates and is protected under applicable intellectual property laws. No part of this content may be copied, reproduced, or exploited in any form without our prior written consent.
          </Text>
        </View>

        {/* Limited License */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Limited License</Text>
          <Text style={styles.contentText}>
            You are granted a limited, non-transferable, and revocable license to access and make personal use of this website. This license excludes any commercial use, unauthorized copying or downloading, or derivative use of any content or product listings.
          </Text>
          <Text style={styles.contentText}>
            Unauthorized use terminates the license granted by 7Miles without prejudice to any legal action we may take.
          </Text>
        </View>

        {/* Your Obligations */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Your Obligations</Text>
          <Text style={styles.contentText}>
            You agree to use the website lawfully and respectfully. You must not attempt to harm the website's functionality or post any content that is offensive, defamatory, or infringes on the rights of others.
          </Text>
          <Text style={styles.contentText}>
            Any breach of these obligations may result in termination of your access and legal action.
          </Text>
        </View>

        {/* Third-Party Links */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Third-Party Links</Text>
          <Text style={styles.contentText}>
            Our website may include links to external websites for your convenience. 7Miles is not responsible for the content, accuracy, or functionality of such third-party websites. Visiting such websites is at your own risk and governed by their respective terms.
          </Text>
        </View>

        {/* Special Promotions and Events */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Special Promotions and Events</Text>
          <Text style={styles.contentText}>
            We may run limited-time offers, promotional campaigns, or events on our website. Participation in such activities may be governed by additional terms and conditions. In case of any conflict, those additional terms shall prevail.
          </Text>
        </View>

        {/* Submissions and User Content */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Submissions and User Content</Text>
          <Text style={styles.contentText}>
            Any feedback, reviews, comments, or suggestions submitted by users ("Submissions") will be treated as non-confidential and non-proprietary. By submitting content, you grant 7Miles the right to use it for any purpose, including marketing and promotional use.
          </Text>
          <Text style={styles.contentText}>
            You represent that your submissions do not infringe any third-party rights and do not contain harmful or unlawful content. We reserve the right to remove any content that violates our policies.
          </Text>
        </View>

        {/* Termination */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Termination</Text>
          <Text style={styles.contentText}>
            We reserve the right to terminate your access or use of the website at our sole discretion, without prior notice, for any conduct that we believe violates these Terms and Conditions or is harmful to the interests of 7Miles or other users.
          </Text>
        </View>

        {/* Disclaimer of Warranties and Limitation of Liability */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Disclaimer of Warranties and Limitation of Liability</Text>
          <Text style={styles.contentText}>
            All products and services are provided "as is" and "as available" unless otherwise stated. We do not guarantee uninterrupted access or error-free service. In no event shall 7Miles be liable for any indirect, incidental, or consequential damages arising from the use of our website or products.
          </Text>
        </View>

        {/* Governing Law and Jurisdiction */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Governing Law and Jurisdiction</Text>
          <Text style={styles.contentText}>
            These Terms and Conditions are governed by and construed in accordance with the laws of India. In the event of any disputes, they shall be subject to the exclusive jurisdiction of the courts located in Namakkal / Tamilnadu.
          </Text>
        </View>

        {/* Contact Us */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Contact Us</Text>
          <Text style={styles.contentText}>
            If you have any questions regarding these Terms and Conditions, you can reach us at:
          </Text>
          <TouchableOpacity onPress={openEmail}>
            <Text style={styles.emailText}>7milesnkl@gmail.com</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 12,
  },
  contentText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 22,
    marginBottom: 12,
  },
  emailText: {
    fontSize: 14,
    color: '#3B82F6',
    fontWeight: '600',
    marginTop: 8,
  },
});

export default TermsOfService;